server:
  port: 8080

spring:
  datasource:
    username: root
    password: zzxaaas
    url: jdbc:mysql://159.75.109.38:2077/elicend?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: cn.zzxcloud.elicend.api.entity
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com:
      example:
        mapper : debug
